version: "3.8"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=ilkin
      - MONGO_PASSWORD=ilkin123123
    command: npm run start:dev