version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ilkin
      - MONGO_INITDB_ROOT_PASSWORD=ilkin123123
    volumes:
      - db_data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data: