version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - db_data:/data/db
volumes:
  db_data: