version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    volumes:
      - db_data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  db_data:
  redis_data: